### ISSUE TITLE
documentation needing additions

### ISSUE THREAD

**Issue by androclus** [my-flow/paypalimporter#11]
as a moneydance user and paypal user, i would like to use this extension, but i cannot get the answers i need from the documentation on the [home page](http://www.my-flow.com/paypalimporter/) or the [README.md](https://github.com/my-flow/paypalimporter).

API_Username, API_Password, and Signature: what ARE these and how do i figure out what mine are (or if I even have these)?

under the Installation section of the home page, it appears one just installs the extension and starts importing transactions. if only it were that easy.

**Comment by my-flow** [comment]
@androclus, thank you for bringing this issue to my attention. I updated the [installation instructions](https://my-flow.github.io/paypalimporter/#installation) on the homepage. I included additional steps on how to acquire username, password, and signature from the PayPal website.
