### ISSUE TITLE
Trying to [re-]install PayPal Importer produces error in Console and unresponsive extension

### ISSUE THREAD

**Issue by crckrmn77** [my-flow/paypalimporter#15]
I recently ran a python script to fix a bank account download issue (USAA) and the PayPal Importer ceased functioning. So, I have tried every way I can think of to uninstall and reinstall the importer, short of reinstalling MoneyDance, and it just will not work--when clicking the Download PayPal Transactions... menu item, nothing happens, and nothing is registered in the Console on the click. I most recently tried installing from a file (downloaded from GitHub) and this is what popped up in the Console:

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: WebView@710a30ae[styleClass=root web-view]is already set as root of another scene
	at javafx.graphics/javafx.scene.Scene$8.invalidated(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.setRoot(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.<init>(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.<init>(Unknown Source)
	at com.moneydance.apps.md.view.gui.bot.RobotBrowser.addToPanel(RobotBrowser.java:289)
	at com.moneydance.apps.md.view.gui.bot.RobotBrowser.lambda$addToPanel$9(RobotBrowser.java:292)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

And when installing via the Extension installer, here is what comes up:

opening connection with no proxy to https://infinitekind.com/app/md/extensions/paypalimporter.mxt
connecting to: https://infinitekind.com/app/md/extensions/paypalimporter.mxt with method: GET proxy: null
CookieHandler request for https://infinitekind.com/app/md/extensions/paypalimporter.mxt
Cookies retrieved: {Cookie=[]}
Sending https request:
GET /app/md/extensions/paypalimporter.mxt HTTP/1.1
Content-Length: 0
Host: infinitekind.com
DNT: 1
Accept-Encoding: gzip, inflate
Connection: close

---end headers
>> GET https://infinitekind.com/app/md/extensions/paypalimporter.mxt 
 <<HTTP/1.1 200 OK
 <<date: Thu, 18 Mar 2021 19:46:01 GMT
 <<server: Apache/2.4.18 (Ubuntu)
 <<vary: Accept-Encoding
 <<last-modified: Wed, 30 May 2018 07:57:52 GMT
 <<etag: "6fd21-56d67b5296000"
 <<accept-ranges: bytes
 <<content-length: 458017
 <<connection: close

trying to verify external module: paypalimporter
trying to verify external module: paypalimporter
initialized extension paypalimporter in 0.004 seconds
opening connection with no proxy to https://infinitekind.com/app/md/extensions.dct
connecting to: https://infinitekind.com/app/md/extensions.dct with method: GET proxy: null
CookieHandler request for https://infinitekind.com/app/md/extensions.dct
Cookies retrieved: {Cookie=[]}
Sending https request:
GET /app/md/extensions.dct HTTP/1.1
Content-Length: 0
Host: infinitekind.com
DNT: 1
Accept-Encoding: gzip, inflate
Connection: close

---end headers
>> GET https://infinitekind.com/app/md/extensions.dct 
 <<HTTP/1.1 200 OK
 <<date: Thu, 18 Mar 2021 19:46:04 GMT
 <<server: Apache/2.4.18 (Ubuntu)
 <<vary: Accept-Encoding
 <<last-modified: Sat, 05 Dec 2020 21:45:12 GMT
 <<etag: "4685-5b5be81f0aa00"
 <<accept-ranges: bytes
 <<content-length: 18053
 <<connection: close

Any ideas?

**Comment by crckrmn77** [comment]
Also, just updated to 2021.1 (3051). I do not recall if I had updated after the install and before running the py script.

**Comment by crckrmn77** [comment]
I rolled back my MD installation to 2021.1 (3036) and the extension is working again. A commenter on TIK discussion boards mentioned it could be an issue with min/max limits. He said, "Build 3051 now obeys min and max build numbers when loading extensions". In case that helps???

**Comment by my-flow** [comment]
The PayPal Importer extension works for me with two beta versions, Mondaydance 2021.1 (**3036**) and Moneydance 2021.1 (**3056**).

As there are a lot of intermediate changes made between preview versions (see [changelog](https://infinitekind.com/previewdl/current/changelog.txt)), it is hard to keep up with compatibility issues. I recommend using the latest _stable_ release version 2021.1 (**2006**).

**Comment by my-flow** [comment]
I confirm that the Paypal Importer extension silently crashes on **macOS** with **Moneydance 2021.1 (3069)** when using the **Default** theme as shown in the screenshot below.
<img width="1061" alt="Screen Shot 2021-06-13 at 9 05 06 PM" src="https://user-images.githubusercontent.com/315457/121837703-20569e00-cc8b-11eb-9297-22e2a289b856.png">

As a temporary work-around, please choose the **Classic** theme.

**Comment by yogi1967** [comment]
… it’s nothing to do with my Python script for usaa. It’s to do with the updated MD where a new Mac LaF called Vaqua was introduced (around build 3054 ish). You must have updated your MD version…. The author needs to update/fix his extensions.

**Comment by my-flow** [comment]
> … it’s nothing to do with my Python script for usaa. It’s to do with the updated MD where a new Mac LaF called Vaqua was introduced (around build 3054 ish). You must have updated your MD version…. The author needs to update/fix his extensions.

Exactly. I have fixed this problem in [release v9](https://github.com/my-flow/paypalimporter/releases/tag/v9) of the PayPal Importer extension. This new [release v9](https://github.com/my-flow/paypalimporter/releases/tag/v9) is currently [queued](https://infinitekind.tenderapp.com/discussions/moneydance-development/6116-new-version-9-of-paypal-importer-extension) and waiting for @sreilly to release it.

**Comment by yogi1967** [comment]
Hi. Can you fix your importlist extension too?

**Comment by my-flow** [comment]
The latest [release v9 of the PayPal Importer extension](https://github.com/my-flow/paypalimporter/releases/tag/v9) is now available as a signed download.
