### ISSUE TITLE
Upgrade to Moneydance 2023.2 (5069) causes the extension to fail

### ISSUE THREAD

**Issue by pdj2225m** [my-flow/paypalimporter#19]
Here is the error when selection the extension:

java.lang.IncompatibleClassChangeError: class
com.moneydance.modules.features.paypalimporter.integration.InitializedOnlineService cannot inherit from final class com.infinitekind.moneydance.model.OnlineService

**Comment by eshicks4** [comment]
Same here.  Tried uninstall/reinstall, download the raw module file and install that way, etc.

**Comment by eshicks4** [comment]
2023.3 update resolved this.  I'm able to pull Paypal successfully again.

**Comment by my-flow** [comment]
The loading error was a temporary regression in Mondaydance 2023.2 (5059). It has been resolved in Moneydance 2023.2 (5061).
