### ISSUE TITLE
Importer sometimes creates duplicate fee transactions 

### ISSUE THREAD

**Issue by dball** [my-flow/paypalimporter#8]
I've only used it to download ~9 months of data at a time thus far, but each time, I've had to track down and remove a few duplicate fee transactions each time.

**Comment by jportway** [comment]
I've had a similar problem where a currency conversion seems to have been duplicated. The plugin is generally great, but this took me hours to track down.

**Comment by my-flow** [comment]
@dball @jportway can you confirm that you see the duplicates only if you use the PayPal Importer extension? When [importing the QIF file from PayPal](http://help.infinitekind.com/discussions/general-questions/1155-how-to-download-from-paypal#comment_3887496), do you see these duplicates as well?

**Comment by jportway** [comment]
Hi - sorry, I've never tried importing a qif from paypal, because they seem to only work in US$ and all my accounts are in £.
